version: "3.9"

services:
  redis:
    image: redis
    ports:
      - "6379:6379"

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  nextjs:
    build: ./headphone-compare-fe
    command: 
    ports:
      - "3000:3000"

  python:
    build: ./headphone-compare-be
    command: python app.py
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - mongodb
    networks:
      my_network:
        ipv4_address: 192.168.1.101

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
